### ISSUE TITLE
Azure hybrid DC/OS deployment: test failure File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 508, in send

### ISSUE THREAD

**Issue by soccerGB** [dcos/dcos-windows#64] opened 2018-05-14 18:33 UTC
# Symptom
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='null', port=5986): Max retries exceeded with url: /wsman (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/tmp/wsmancmd.py", line 155, in 
main()
File "/tmp/wsmancmd.py", line 148, in main
cert_key_pem, cmd)
File "/tmp/wsmancmd.py", line 111, in run_wsman_cmd
shell_id = p.open_shell(codepage=65001)
File "/usr/local/lib/python3.5/dist-packages/winrm/protocol.py", line 132, in open_shell
res = self.send_message(xmltodict.unparse(req))
File "/usr/local/lib/python3.5/dist-packages/winrm/protocol.py", line 207, in send_message
return self.transport.send_message(message)
File "/usr/local/lib/python3.5/dist-packages/winrm/transport.py", line 173, in send_message
response = self.session.send(prepared_request, timeout=self.read_timeout_sec)
File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 618, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 508, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='null', port=5986): Max retries exceeded with url: /wsman (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -2] Name or service not known',))
ERROR: Failed to get the Docker container ID from the host: null
ERROR: Failed to test Mesos fetcher using remote http resource
Collecting logs from all the DC/OS nodes
Collecting Linux master logs
Collecting Linux agents logs
Collecting Windows agents logs
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed

**Comment by ionutbalutoiu** [comment] 2018-05-16 11:17
This `Name or service now known` errors were caused by DNS failures. 

The PR https://github.com/dcos/dcos-windows/pull/65 fixed these issues and I haven't seen this error anymore in the CI.

Closing this issue for now.

**Closed by ionutbalutoiu** 2018-05-16 11:17 UTC
